import type { Metadata } from "next";
import { Rubik, Lora } from "next/font/google";
import { Toaster } from "react-hot-toast";
import Provider from "~/lib/providers";
import "~/app/globals.css";

const rubik = Rubik({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-rubik",
});
const lora = Lora({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-lora",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${rubik.variable} ${lora.variable} font-rubik`}>
        <Toaster />
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
